### ISSUE TITLE
table formatting

### ISSUE THREAD

**Issue by leder11011** [ttscoff/mdless#102]
Hello Brett,

you once had a flowing table formatting right?

Please fix the formatting seen in the attachment.

Best regards
Gerrit
![Bildschirmfoto vom 2024-09-27 07-55-00](https://github.com/user-attachments/assets/7d8ee4e4-21c3-4638-8692-c7917044dfcb)

**Comment by ttscoff** [comment]
I’m confused, the table in the image looks great to me. What is the issue?

Thanks,
Brett

**Comment by leder11011** [comment]
as you can see in this screenshot with a selction in the table: The right edges of the lines are not aligned.

![Bildschirmfoto vom 2024-09-27 17-29-18](https://github.com/user-attachments/assets/3622bf11-b7e5-4424-b477-52cbbc76fd64)

**Comment by ttscoff** [comment]
Oh I see it now. Will have to look into it when I have some time.

**Comment by leder11011** [comment]
That would be fine!

Brett Terpstra ***@***.***> schrieb am Fr., 27. Sept. 2024,
17:53:

**Comment by ttscoff** [comment]
Could you provide me with the Markdown for the table you show in your example? My test tables are working fine in this regard, need to figure out what's different about yours.

**Comment by ttscoff** [comment]
Oh I know what it is. The linked emails are throwing off the character count for the line, need to accommodate the difference created by highlighting those. Your sample file would be of great help for testing.

**Comment by leder11011** [comment]
I would like to provide you with the java app:
I do pipe the markdown output of the app to mdless - this may be unconventional. As an alternative I write the output to a file and give it to you...

[burzltag app](https://burzltag.herokuapp.com/download/)

**Comment by leder11011** [comment]
[burzltag.txt](https://github.com/user-attachments/files/17192280/burzltag.txt)

**Comment by ttscoff** [comment]
This should be fixed as of 2.1.46. Hopefully I didn't break anything 
else in the process.

-Brett

**Comment by leder11011** [comment]
looks fine to me! Thank you very much!
