### ISSUE TITLE
Messages about no 'imgcat' and no 'pager' displaying before printing out markdown

### ISSUE THREAD

**Issue by blakesisu** [ttscoff/mdless#16]
The message for both starts as `which: no imgcat in (<all:the:paths>)` and it's the same thing for 'pager'. The app still works as expected otherwise, but this is kind of strange. I'm using urxvt in manjaro i3, and zsh.

**Comment by colincci** [comment]
I am seeing the same thing in RHEL7.6 and bash.  Is there a link or a gem missing?

**Comment by ttscoff** [comment]
imgcat is part of iTerm2 on Mac. I may have left a debug message in 
there somewhere...

**Comment by kuczaQ** [comment]
imgcat is like cat, but for images... it should be in the repos (on arch it's in AUR)

**Comment by ttscoff** [comment]
Fixed in next update.
