### ISSUE TITLE
Indenting of heading list does not account for length of index

### ISSUE THREAD

**Issue by smithkm** [ttscoff/mdless#18]
```markdown
# a
## b
## c
## d
## e
# f
## g
## h
## i
## j
## k
## l
```
Running `mdless -lP headings.md` gives. 
```

1: a
2: ..- b
3: ..- c
4: ..- d
5: ..- e
6: f
7: ..- g
8: ..- h
9: ..- i
10: ..- j
11: ..- k
12: ..- l

```

note how j, k, and l are all shifted over an extra space.  With the `..`s hidden when on a colour terminal, it can appear at first glance that there is an additional level in the heirarchy.

**Comment by ttscoff** [comment]
Finally got this fixed in 1.0.1, should be available on the gem server now.
