### ISSUE TITLE
Stalls when trying to display doing files

### ISSUE THREAD

**Issue by pax** [ttscoff/mdless#19]
mdless stalls when attempting to render [doing](https://github.com/ttscoff/doing/) markdown files. 

also tried with cat.
script freezes, then upon Ctrl + C I get this message:

```
  ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/lib/mdless/converter.rb:338:in `sub!': Interrupt
  from ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/lib/mdless/converter.rb:338:in `convert_markdown'
  from ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/lib/mdless/converter.rb:118:in `block in initialize'
  from ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/lib/mdless/converter.rb:106:in `each'
  from ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/lib/mdless/converter.rb:106:in `initialize'
  from ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/bin/mdless:17:in `new'
  from ~/.rvm/gems/ruby-2.3.1/gems/mdless-0.0.10/bin/mdless:17:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.3.1/bin/mdless:23:in `load'
  from ~/.rvm/gems/ruby-2.3.1/bin/mdless:23:in `<main>'
  from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

\* while trying to render my doing file as an [Übersicht](http://tracesof.net/uebersicht/) widget

**Comment by ttscoff** [comment]
In general doing files are not Markdown, they're TaskPaper format. That said, while the highlighting isn't ideal, you should no longer get errors on them.

I might consider special handling for these in the future, but doing has its own output formatting features that offer a lot more power...
