### ISSUE TITLE
`mdless` not properly showing code blocks

### ISSUE THREAD

**Issue by jjarava** [ttscoff/mdless#2]
Hi!

I've just installed mdless and I've noticed there seem to be some issues with the way that code blocks are shown. I have `Pygments` installed, and (apparently; not very familiar with it) working:

``` bash
test$ pygmentize -V
Pygments version 2.0.2, (c) 2006-2014 by Georg Brandl.
```

I've created a test file but due to GitHub's funky Issues app not allowing attachments, I've posted it as a gist (https://gist.github.com/jjarava/9596855f9f1ff9720167).

For reference, this is how the example file looks when viewing it on Marked - notations 1, 2 and 3 work fine

![mdless-example-marked-2015-09-07_17-46-08](https://cloud.githubusercontent.com/assets/2682444/9719809/7436f644-5588-11e5-98ea-fee84892cf3b.jpg)

The same file viewed with `mdless` within iTerm 3 beta shows several issues:

![mdless-example-mdless-iterm3-beta-2015-09-07_18-10-46](https://cloud.githubusercontent.com/assets/2682444/9720162/ea3c3a68-558b-11e5-9a7e-1744be318ee3.jpg)

Running the same file through `pygmentize` via `cat mdless-sample-test.md | pygmentize` shows that the syntax highlighting is working (or at least the script would recognize quite a few of the snippets):

![mdless-example-raw-pygmentize-2015-09-07_18-13-45](https://cloud.githubusercontent.com/assets/2682444/9720208/63637334-558c-11e5-950f-d0c95cdbb913.jpg)

Any hints or workarounds more than welcome; personally I'm quite partial to the triple backtick notation in my .md files and I've got more than a few code samples scattered in my files...

Regards

**Comment by ttscoff** [comment]
This should be significantly improved in the latest release. Let me know if you still have issues.
