### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by liamdawson** [ttscoff/mdless#26]
Hi! I'm about to use this tool (thanks!) but I noticed there haven't been releases since Jan 2018, whereas there seem to be a few juicy PRs. Would you mind cutting another release? 🙂

**Comment by ttscoff** [comment]
All PRs merged, new 0.0.11 release is up. Hopefully I didn't break anything in the process...

**Comment by bexelbie** [comment]
Can we get a new gem release too?

**Comment by ttscoff** [comment]
1.0 is out now, pushed to gem server.
