### ISSUE TITLE
mdless not showing code blocks at all

### ISSUE THREAD

**Issue by ronangaillard** [ttscoff/mdless#31]
In `mdless` this :

````
Vérifier que les sous-modules Git ont bien été clonés :

```
git submodule update --init
```

````

Would show as 

<img width="503" alt="image" src="https://user-images.githubusercontent.com/5607736/61055431-c17ab100-a3f1-11e9-81b4-9b4ac33be7f9.png">

I'm using iTerm2 build 3.2.5 with mdless 0.0.12

**Comment by BenKettlewell** [comment]
I'm getting the following stack trace as well whenever the markdown has a code block. It works fine as long as there's no code.
I'm also using mdless 0.0.12 but a standard Ubuntu shell.

```
Traceback (most recent call last):
        8: from /usr/local/bin/mdless:23:in `<main>'
        7: from /usr/local/bin/mdless:23:in `load'
        6: from /var/lib/gems/2.5.0/gems/mdless-0.0.12/bin/mdless:17:in `<top (required)>'
        5: from /var/lib/gems/2.5.0/gems/mdless-0.0.12/bin/mdless:17:in `new'
        4: from /var/lib/gems/2.5.0/gems/mdless-0.0.12/lib/mdless/converter.rb:133:in `initialize'
        3: from /var/lib/gems/2.5.0/gems/mdless-0.0.12/lib/mdless/converter.rb:437:in `convert_markdown'
        2: from /var/lib/gems/2.5.0/gems/mdless-0.0.12/lib/mdless/converter.rb:437:in `gsub!'
        1: from /var/lib/gems/2.5.0/gems/mdless-0.0.12/lib/mdless/converter.rb:457:in `block in convert_markdown'
/var/lib/gems/2.5.0/gems/mdless-0.0.12/lib/mdless/converter.rb:324:in `hiliteCode': undefined method `split' for nil:NilClass (NoMethodError)
```

**Comment by ttscoff** [comment]
I'm not experiencing this with 0.0.12 on my Mac, wondering if it's OS 
specific.

**Comment by ronangaillard** [comment]
I'm using OSX also

**Comment by JaviCerveraIngram** [comment]
Same problem here on Linux Mint 19.1 (based on Ubuntu 18.04).

**Comment by ttscoff** [comment]
Ok, I'm getting this behavior on macOS Mojave as well now, I'll look into it.

**Comment by ttscoff** [comment]
Ok, pushed gem for 0.0.13, and source is updated in code and releases page. Give it a whirl and let me know if it doesn't solve the issue for you.

**Comment by ttscoff** [comment]
Yeah, I was seeing the broken escapes occasionally but thought I had 
fixed it. It seems to be an error in pygments caused by passing an 
invalid lexer to it, which is derived from the language on the code 
block (or falls back to a hashbang if it exists). I might just need to 
have it ensure a valid lexer and default to letting pygments guess if it 
doesn't have one.

I'll update as soon as I'm able.

Thanks,
Brett

**Comment by ttscoff** [comment]
That ¬ character is intentional. I found that with the way I changed some of the highlighting, it was helpful to see where wrapped lines actually ended. I plan to make it customizable/optional in an upcoming release.
