### ISSUE TITLE
hiliteCode undefined method split

### ISSUE THREAD

**Issue by echorebel** [ttscoff/mdless#32]
just installed and tried mdless
and got
```
/Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:324:in `hiliteCode': undefined method `split' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:457:in `block in convert_markdown'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:437:in `gsub!'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:437:in `convert_markdown'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:118:in `block in initialize'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:106:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/lib/mdless/converter.rb:106:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/bin/mdless:17:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/mdless-0.0.12/bin/mdless:17:in `<top (required)>'
	from /usr/local/bin/mdless:22:in `load'
	from /usr/local/bin/mdless:22:in `<main>'
```

any clue how to fix it?

**Comment by ttscoff** [comment]
What operating system?

-Brett

**Comment by sqren** [comment]
I'm getting exactly the same error. 

macOS Mojave 10.14.5 (18F132).
Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

Any other details needed?

**Comment by ttscoff** [comment]
No additional details needed, I can totally test that scenario, but it's 
unlikely I'm going to have time to look into this in the next couple of 
weeks. If anyone does track down the bug, I'll absolutely merge a pull 
request.

-Brett

**Comment by lcorsini** [comment]
that function fails if it cannot find the pygmentize binary, after a pip install pygments it works fine

**Comment by echorebel** [comment]
yep that worked for me too!

**Comment by tbarbette** [comment]
Same thing here on Ubuntu server 18.04. After installing mdless with "snap install mdless" I get the same error.

**Comment by ttscoff** [comment]
Should be fixed in the latest release. Please `gem update mdless` and let me know if you still have any issues.
