### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by kkerchmar** [ttscoff/mdless#33]
Hi, would you please consider adding an open source LICENSE file to this project? I am interested in using it, but I am restricted from doing so without an explicit license specified by the project. Thank you!

**Comment by ttscoff** [comment]
Done. Added MIT, happy to reconsider if you think there's a more 
appropriate license.

Thanks,
Brett

**Comment by kkerchmar** [comment]
Thank you, that is fantastic.
