### ISSUE TITLE
`mdless` v1.0.2 rendering of headers issues when there's no "H1" header

### ISSUE THREAD

**Issue by jjarava** [ttscoff/mdless#35]
Hi, 

Just testing the new version of `mdless` (v1.0.2), I've found it has some issues for showing header levels when the files does not a "H1" (single `#`) line.

If the file has level 2 (`##`) or level 3 (`###`) headers, they are shown like normal lines, but with one "hash" less on the line.

So, this text:

```
Sample text
## Level 2
some text
### Level 3
some more text
```
is shown like this:

![image](https://user-images.githubusercontent.com/2682444/64886055-9ae12c80-d665-11e9-89cd-66b5361996bb.png)

I've created another example file that is attached (as a zip) to the issue.

[sample-mdless-missing-header.md.zip](https://github.com/ttscoff/mdless/files/3611344/sample-mdless-missing-header.md.zip)

Thanks!

**Comment by ttscoff** [comment]
This is by design. It assumes that your document structure starts at the 
highest header, h2 in this case, so it translates that to h1 and 
cascades the remaining structure from there. I'm willing to debate the 
utility of this, but it was an intentional decision. I use a similar 
method in my own work using MutliMarkdown base-header-level settings.

-Brett

**Comment by jjarava** [comment]
Hi!

But if that's the case (i.e. you're assuming in this document "Top level H2 ==> H1"), then wouldn't it make sense to highlight it? I could understand that you decided to highlight it as a "normal" H1 and then cascade down from there, _or_ just assume "there's no H1, so it's syntactically broken" and just show it as plain text -- but not highlighting **and** "changing the header level" is what seems odd, as it's like taking a bit of both options (and the "strange" part, at that)...   

To be honest, the reason I don't use H1 as first header is b/c on many apps (e.g., Airmail) H1 is very often associated with a page break,, and it's too large for a "section header"... So I tend to use H2 or even H3 as the "highest" level header on many of my docs....

What is interesting is that other apps (e.g. Marked 😉) do render the document fine.

Just my 0.002

**Comment by ttscoff** [comment]
I removed this "feature" for the latest release (1.0.3). Also, the 
failure to highlight after converting was definitely a bug.

-Brett

**Comment by jjarava** [comment]
Cool - thanks for the change.

Now, I've just updated to the latest (1.0.3) and it's not working -- but that's for another issue (#36); I'll be closing this one.
