### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by MiniCodeMonkey** [ttscoff/mdless#37]
This is a super neat tool! Just what I needed!

I have a weird rendering issue though, and would appreciate any pointers to fix it. Code text appears outlined which makes it very difficult to read.

I am using Hyper 3 on macOS Mojave with zsh and Menlo as the font.

<img width="1584" alt="Screen Shot 2019-11-12 at 10 23 10 AM" src="https://user-images.githubusercontent.com/220535/68684579-b61dca80-0536-11ea-811a-6b57996380a9.png">

Thanks!

**Comment by ttscoff** [comment]
That is really weird, not something that's even possible in a native terminal. I don't have any experience with Hyper 3, but I'd be 99% sure that's where the problem lies. You might be able to use a custom theme to find color settings that _didn't_ do that in Hyper.

**Comment by ttscoff** [comment]
And by custom theme, I mean one [for mdless](https://github.com/ttscoff/mdless#customization).

**Comment by MiniCodeMonkey** [comment]
Thanks! I'll try that out.
