### ISSUE TITLE
mdless (1.0.5) exiting with no output on OSX 10.15 (previously worked)

### ISSUE THREAD

**Issue by ghost** [ttscoff/mdless#38]
I was using mdless for a few weeks and it's suddenly started exiting with no output. Tried the -d flag but the only output is:

~ > mdless -d test.md
Error: Log level out of range (1-4)

Any idea what might be going on? Would love to track down the error and get back to using it.

**Comment by ttscoff** [comment]
The -d switch requires a log level, 1-4. Try `mdless -d 4 test.md`.

**Comment by sobodash** [comment]
~ > mdless -d 4 test.md
W, [2019-11-18T18:56:32.769840 #49956]  WARN -- : Error merging user theme
I, [2019-11-18T18:56:32.769974 #49956]  INFO -- : Processing "test.md"
I, [2019-11-18T18:56:32.850276 #49958]  INFO -- : Using ["bat", ""] as pager
~ >

**Comment by ttscoff** [comment]
Did you edit a custom theme?

- Brett

**Comment by sobodash** [comment]
This does not appear to be the case:

`~ > rm -rf ~/.config/mdless
~ > mdless -d 4 test.md
I, [2019-11-19T01:49:06.072215 #50214]  INFO -- : Creating config directory at /Users/d/.config/mdless
I, [2019-11-19T01:49:06.072525 #50214]  INFO -- : Writing fresh theme file to /Users/d/.config/mdless/mdless.theme
W, [2019-11-19T01:49:06.074716 #50214]  WARN -- : Error merging user theme
I, [2019-11-19T01:49:06.074785 #50214]  INFO -- : Processing "test.md"
I, [2019-11-19T01:49:06.130503 #50216]  INFO -- : Using ["bat", ""] as pager
~ >`

**Comment by ttscoff** [comment]
I'm not sure what to tell you. Were there any major changes to your 
system between the time it worked and the time it didn't?

**Comment by daneah** [comment]
FWIW I'm experiencing this as a brand new user to mdless! I'd love to provide additional data if there's anything useful to be had from it:

macOS version: 10.14
Ruby version: 2.5.1
iTerm2 version: 3.3.6
What didn't work: Everything seems in order except the fenced code blocks for me, with/without pygments installed.
What I tried: Installing pygments, trying a few files with different programming languages represented
Am I using a custom theme: nope

```shell
$ cat ~/.config/mdless/mdless.theme
--- default

$
```

**Comment by ttscoff** [comment]
@sobodash what do you get when you `cat ~/.config/mdless/mdless.theme`? What @daneah shows is definitely not right.

Also, @daneah , are you saying that it's working fine except for fenced code blocks? If that's the case, you need to open a separate ticket. This ticket refers to zero output happening.

**Comment by ttscoff** [comment]
Just tested after deleting my `mdless.theme` and it wrote out what @daneah is showing. Still works, but that's definitely why it says there's an error merging. I'll dig into that, though I think it's separate from whatever @sobodash is experiencing.

**Comment by ttscoff** [comment]
Pushed v1.0.6 to the repo and to the gem server. It fixes the theme issue, so update to that before testing any further and let me know where we're at.

**Comment by sobodash** [comment]
I decided to remove all gems, purge the gem directory, and reinstall. This is the output of mdless -d 4 with the newest version.

> ~ > gem uninstall -aIx
> Removing mdless
> Successfully uninstalled mdless-1.0.8
> INFO:  Uninstalled all gems in 
> ~ > gem install mdless
> Fetching mdless-1.0.8.gem
> Successfully installed mdless-1.0.8
> invalid options: -ri
> (invalid options are ignored)
> Parsing documentation for mdless-1.0.8
> Installing ri documentation for mdless-1.0.8
> Done installing documentation for mdless after 0 seconds
> 1 gem installed ~ > mdless -d 4 test.md
> I, [2019-11-26T13:24:15.084004 #70433]  INFO -- : Processing "test.md"
> I, [2019-11-26T13:24:15.162317 #70435]  INFO -- : Using ["bat", " -p"] as pager
