### ISSUE TITLE
Fenced code blocks render as empty

### ISSUE THREAD

**Issue by daneah** [ttscoff/mdless#39]
When viewing a file with `mdless`, code blocks render without any text in them:

    $ cat foo.md
    ```python
    def foo(bar):
        print("yay!")
    ```
    
    $ mdless foo.md
    --[ python ]-------------------------------
    -------------------------------------------

macOS version: 10.14
Ruby version: 2.5.1
iTerm2 version: 3.3.6
What didn't work: Everything seems in order except the fenced code blocks for me, with/without pygments installed.
What I tried: Installing pygments, trying a few files with different programming languages represented, removing `~/.config/mdless/mdless.theme`
Am I using a custom theme: nope

```shell
$ cat ~/.config/mdless/mdless.theme
--- default

$
```

**Comment by ttscoff** [comment]
The theme issue is fixed in 1.0.6 (just pushed), but I don't think it will fix this issue. 

Does running `pygmentize foo.md` do any highlighting? It won't be right, but it should output something.

**Comment by ttscoff** [comment]
BTW, you'll want to delete `~/.config/mdless/mdless.theme` before running the updated version to let it write out a correct theme.

**Comment by daneah** [comment]
I just updated (looks like you've got 1.0.8 out already!) and code block contents are indeed appearing now. They also show syntax highlighting when `pygmentize` is on `PATH`. Thank you 🎉
