### ISSUE TITLE
Headlines with parentheses, question marks not parsed as headlines

### ISSUE THREAD

**Issue by ernstki** [ttscoff/mdless#42]
Headlines that contain certain characters (which look like they could be regex metacharacters) do not get parsed as headlines. I haven't done an exhaustive search, but I've noticed that parentheses and question marks are among the characters that cause this.

I'm using version 1.0.9 freshly installed with `gem install` on macOS Mojave (10.14), with the built-in Ruby 2.3.7something.

Given this input, I expect all three headlines to be parsed correctly:

```
mdless <(echo "# A header (with parentheses)

Words.

## a subheader - with a question mark?

Words, words.

## a subheader with no funny stuff

Words, words, words.")
```

…but only the third headline "a subheader with no funny stuff" actually is. The output looks like this:

![test_with_funny_chars_thumb](https://user-images.githubusercontent.com/4009681/72390032-bfbedc80-36f7-11ea-8383-c40d067e370a.png)

If you remove the offending characters (parentheses and question marks in this example), you get the expected output:

![test_no_funny_chars_thumb](https://user-images.githubusercontent.com/4009681/72390076-dcf3ab00-36f7-11ea-922c-a8525a2bd847.png)

I'm no whiz at the `git bisect`ing, but I'm pretty sure this behavior didn't exist a year or so ago, when I was using `mdless` to run terminal-based "slideshows" for a workshop.

**Comment by ernstki** [comment]
@ttscoff  I'm happy to do a PR (and even include tests that catch the above bad behavior) if you can give me a gentle push in the right direction.

Since I'm not a real Ruby developer, my efforts of getting something to even run after `git clone`ing the repository were somewhat frustrated at the `bundle install` step, when `bundle exec rake` just gave me a backtrace (#43).

**Comment by ttscoff** [comment]
Found the issue (needed Regexp.escape), pushed v1.0.10 (to rubygems and 
to this repo)

Thanks!
