### ISSUE TITLE
Exits with `sh: 1:git: not found`

### ISSUE THREAD

**Issue by chrisbeardy** [ttscoff/mdless#54]
After viewing a file and then when quitting with `q` I get the follwoing ouput on my shell:

`sh: 1:git: not found`
![image](https://user-images.githubusercontent.com/20585410/85200653-38524680-b2f1-11ea-9c34-74179cde70cf.png)

**Comment by chrisbeardy** [comment]
just realised git was installed by default in the VM i was using and that its being used to get the pager to pipe the output too.

**Comment by ttscoff** [comment]
It checks for a git page to be specified, but it’s bad form that it errors without git. When I have a minute I’ll put a rescue block on that.

- Brett
