### ISSUE TITLE
Greater than & space in front of code block content & line break symbol at the end of line

### ISSUE THREAD

**Issue by jonnyhoff** [ttscoff/mdless#55]
OS: Fedora 32

When reading files with code blocks I can't copy the content because of the extra greater than & space in front of code block content & line break symbol at the end. Is there a way to disable this? if not, please add this feature.

```
--[ code ]----------------------------------------------------------------------------------------------------------------------------
> some commad¬                                                                                                     
> some other commad¬                                                                                                     
--------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ttscoff** [comment]
It’s assumed that since you’re dealing with text on the command line you can always use the near-infinite number of other Unix text tools to extract text (like less?). Mdless is designed as a viewer, so I’m not sure catering to copy/paste is my top priority.

- Brett

**Comment by jonnyhoff** [comment]
The point of using `mdless` is to have my markdown notes more readable directly on the cli but losing the ability to copy multi line code is a simply thing that would make me use your tool more regularly and probably not the only one that feels this way, I'm sure you can understand this but your attitude just convinced me to rather use another cli markdown tool called `glow` (who's tool displays code without irrelevant characters).

- Jonny

**Comment by javipolo** [comment]
I'm in the same page as @jonnyhoff so +1 to this request :)

**Comment by ttscoff** [comment]
I'm not married to the `>` at all, if it's an issue for people I'm fine with just not including it in the output. Try version 1.0.18 and see if it works for you.

**Comment by ttscoff** [comment]
BTW. you should now have the choice to exclude the prefix character in the theme:

```yaml
code_block:
  character: ''
```

That should remove it entirely, though there's another issue open where this causes the code block to blink (which I don't understand yet). Please test and let me know.
