### ISSUE TITLE
Does not resolve HTML Escape Codes

### ISSUE THREAD

**Issue by stefanwascoding** [ttscoff/mdless#57]
Currently `mdless` does not unescape HTML character codes like `&nbsp;` or `&szlig;`

![escape](https://user-images.githubusercontent.com/2292035/98980891-8c1e3000-251d-11eb-90bd-b68703941ff6.png)

**Comment by ttscoff** [comment]
mdless highlights syntax, it does no actual processing of Markdown, let alone HTML.

Thanks,
Brett
