### ISSUE TITLE
mdless does not render HTML escaped characters

### ISSUE THREAD

**Issue by atsaloli** [ttscoff/mdless#64]
Hi again,

Is it possible for `mdless` to render HTML escaped characters, please? I need to be able to put a pipe into a markdown table.

```
[root@my-hostname-has-dashes source]# cat /tmp/ex.md
Logical operators (in order of precedence of operation)

| Operator   | Description |
|------------|-------------|
| `( )`      |  Grouper
| `!`        | NOT
| `&` or `.` | AND
| &#124;     | OR

[root@my-hostname-has-dashes source]# mdless /tmp/ex.md
Logical operators (in order of precedence of operation)

+------------+-------------+
| Operator   | Description |
|------------|-------------|
| `( )`      | Grouper     |
| `!`        | NOT         |
| `&` or `.` | AND         |
| &#124;     | OR          |
+------------+-------------+





[root@my-hostname-has-dashes source]# pandoc -o /tmp/example.txt /tmp/ex.md
[root@my-hostname-has-dashes source]# cat /tmp/example.txt
Logical operators (in order of precedence of operation)

  Operator     Description
  ------------ -------------
  `( )`        Grouper
  `!`          NOT
  `&` or `.`   AND
  |            OR


[root@my-hostname-has-dashes source]#
```

https://www.markdownguide.org/extended-syntax/#:~:text=Escaping%20Pipe%20Characters%20in%20Tables,(%20%7C%20) says:  
> You can display a pipe (|) character in a table by using its HTML character code (&#124;).

Pandoc is able to handle this just fine.

**Comment by ttscoff** [comment]
Pandoc isn't outputting to the terminal. A lot of HTML entities would display poorly in many terminals, and I don't really want to add a whole lookup table to convert them. That's partly just laziness, but it's also a pretty large undertaking for a little command line utility.
