### ISSUE TITLE
Backslash appears in mdless output

### ISSUE THREAD

**Issue by atsaloli** [ttscoff/mdless#65]
Hello,

I've run into an issue where a backslash appears in mdless output instead of just making the next character be not special -- see line 1 of the following example:

```
[root@localhost source]# cat 320-150-Editing_Files-0070-replace_patterns_and_edit_field.md
There are two other promise types you can make in edit\_line bundles:

**replace\_patterns**
: search and replace

**edit\_field**
: columnar editing

We will look at them later.
[root@localhost source]# mdless 320-150-Editing_Files-0070-replace_patterns_and_edit_field.md
There are two other promise types you can make in edit\_line bundles:


**replace_patterns**
: search and replace

**edit_field**
: columnar editing

We will look at them later.




[root@localhost source]#
```

Notice that the backslash is handled correctly in the `replace_patterns` and `edit_field` lines, but not in teh first line.

**Comment by atsaloli** [comment]
Workaround is to add a header -- then the backslash disappears from the output.

**Comment by ttscoff** [comment]
mdless isn't actually rendering markdown, just coloring/highlighting it, and currently isn't smart enough to recognize backslashed characters as escapes.
