### ISSUE TITLE
extra red on black blocks in mdless output on RHEL 7.9

### ISSUE THREAD

**Issue by atsaloli** [ttscoff/mdless#67]
Hello,

I just switched to a RHEL 7.9 system and now mdless output includes extra red on black blocks after headers and in code blocks:

![image](https://user-images.githubusercontent.com/508704/106365716-3b340180-62ec-11eb-821c-a814e915fbdc.png)

Any ideas what might be wrong and how to fix it, please?

RHEL 7.9 is a customer requirement, not my choice necessarily; in other words, I'm stuck with it.

**Comment by atsaloli** [comment]
Of course, I don't have anything like that in my markdown source code.

Here it is (vim "set list" enabled to show special chars such as end of line):

![image](https://user-images.githubusercontent.com/508704/106365764-85b57e00-62ec-11eb-9e68-6d31d673b6c6.png)

**Comment by atsaloli** [comment]
This only happens when I run `mdless` in `vim` using the Vim Terminal facility.  

This doesn't happen when I run mdless on the command line.

My vimrc has something ilke:

```
:autocmd BufRead *.md :term++curwin mdless %:p
```

**Comment by ttscoff** [comment]
No idea what's going on here. I tested your command in Vim on my Mac and got the correct results. I'm not a vim expert, though, and really have no idea where to look for this issue.

**Comment by atsaloli** [comment]
No worries. I ended up not using the Vim Terminal, just used the shell directly.
