### ISSUE TITLE
Change file extension from `.theme` to `.yaml`

### ISSUE THREAD

**Issue by anishmittal2020** [ttscoff/mdless#69]
Change file extension from `.theme` to `.yaml` so that editors can use yaml colours and can identify syntax error.

**Comment by ttscoff** [comment]
Can't you just tell your editor that the syntax is YAML? I'm not 
entirely opposed to changing the extension, but it would be a breaking 
change for any users with custom themes. To be backwards compatible I 
would have to make it support both, which would take some rewriting.

-Brett

**Comment by anishmittal2020** [comment]
I don't mind. But I think you can have it in your mind during next major release where you are planning some breaking changes.
