### ISSUE TITLE
math equations ($$)

### ISSUE THREAD

**Issue by Peshkatar** [ttscoff/mdless#81]
Math equations not rendering in terminal (iterm2) on mac (ventura).

**Comment by ttscoff** [comment]
mdless has no processing for math. If it were to handle it, what would you expect it to output? Equations are out of the question in Terminal…

**Comment by rwmitchell** [comment]
If the equation could be converted into an image, it could be displayed in terminals supporting inline images.

I use this method to display a login banner with multiple fonts:

![image](https://github.com/ttscoff/mdless/assets/15944841/b3d87fec-d546-45c5-bf20-fca6f5dcc480)

(it displays after the first command to avoid instant prompt warnings....)

**Comment by ttscoff** [comment]
This is beyond the scope of what mdless hopes to do, sorry. If you can 
make it happen, I'd accept a pull request, but I'm not going to put time 
into figuring this out. You'd probably have to mix JS in with the ruby, 
and might even need a chromeless browser to render it... too much 
effort.

-Brett

**Comment by rwmitchell** [comment]
fully concur!  I couldn't find any easy way to convert equations without installing new packages.
