### ISSUE TITLE
how to set image width and height

### ISSUE THREAD

**Issue by tissatussa** [ttscoff/mdless#82]
i'm on Xubuntu 22.04 and mdless compiles and runs well .. but image rendering is "raw", a 128x128 png is shown as big as half the page ! So, mdless does not interpret any width / height attributes : how to add those ?

also it's unclear to me what resolution and minimal image size we can expect : what can a terminal display ? I can use Xterm and Konsole, both terminals normally function well on my OS.

**Comment by ttscoff** [comment]
mdless simply passes image paths to whatever image display tool is 
available on the system, no attributes can be interpreted. The display 
of the image will be determined by the tool available.

**Comment by tissatussa** [comment]
thanks.
i installed Chafa before running mdless, as written on your webpage - i didn't know Chafa but default apt (by Synaptic) install went well .. should i adjust some setting for it ?

**Comment by tissatussa** [comment]
> ..no attributes can be interpreted..

but i often see those attributes in readme.md files .. Okular seems to interpret them well, but Okular does not show remote images, i don't know why, for now a solution is your mdless tool ..   Btw. i also encounter many readme.md files with inaccurate markdown (eg. no empty line, etc) so display will then be corrupt anyhow .. until now mdless seem to function / interpret OK, it even has coloring, which i like.

**Comment by ttscoff** [comment]
Sure, images can have attributes in most flavors of Markdown, but mdless 
can't do anything with them.

-Brett

**Comment by tissatussa** [comment]
OK.
and is image display (although giving much too big images now) done on my OS by Chafa now ? how can i know ? And should i study Chafa and find / edit its settings, if possible ? I know very few terminal applications that display images in terminal - can you point me to more info about this topic ?

**Comment by ttscoff** [comment]
Yes, chafa is displaying the images. You can see chafa options by 
running `chafa --help`, but you would have to edit the mdless gem to 
implement any of them, and I don't believe size constraints are among 
the available options.

https://hpjansson.org/chafa/

-Brett

**Comment by tissatussa** [comment]
that's clear .. i'm not a beginner at Linux and i can do some config edit, module installs etc. but those display issues and techniques are new to me. I must be able to solve my issue now, thanks for the info, i learned lot about markdown today, and i found your mdless !
