### ISSUE TITLE
Request support for Alactritty Terminal Emulator

### ISSUE THREAD

**Issue by speightashley** [ttscoff/mdless#84]
Operating System: Manjaro Linux
DE: Gnome 43
Terminal: Alacritty

Issue: Can't open MD files properly with Mdless in Alacritty. I get a *Tput: Unknown Terminal Alacritty*

I moved to Alacritty from Gnome terminal a a couple of months ago and can't move back to Gnome terminal now because it's just awesome.

The problem I have is MDless isn't supported on Alacritty.

Is there any scope for introducing support for this terminal emulator?

I can open MD files with MDless in the terminal but it just isn't formatted properly.

**Comment by ttscoff** [comment]
mdless uses `tput` to determine the width of the terminal. I might be 
able to replace it with a different method, but I can't be sure it 
wouldn't run into the same issue. The easy fix should be to set your 
$TERM environment variable before running mdless.

	export TERM=xterm

... should do the trick. You can change it _only_ when running mdless by 
aliasing `mdless="TERM=xterm command mdless"`. Let me know if that 
helps.

-Brett

**Comment by speightashley** [comment]
Aliasing worked like a dream Brett. Didn't fancy changing the environment variable for the terminal every time I wanted to view a MD document :-D

My dev environment is Tmux, Nvim and other terminal apps so it would get a bit messy if I'm changing variables for different terminals mid flow.

It's a good piece of kit this mdless though. Consider it starred :-D
