### ISSUE TITLE
How to use built-in pager?

### ISSUE THREAD

**Issue by rwmitchell** [ttscoff/mdless#85]
newbie here - just found this, looks really nice.

I'm using iTerm2.  If I unset PAGER, then mdless uses it's built in pager and images display as desired.

I'd prefer not to unset PAGER.  Is there a flag or setting I can use to get the built in pager?

follow-up: can the path to imgcat be specified?

**Comment by ttscoff** [comment]
What is your PAGER set to? mdless defaults to $PAGER, then $GIT_PAGER, 
then `git config --get-all core.pager` if that's set, then cycles 
through bat, less, more, cat, and pager, in that order, looking for an 
available option. If you're unsetting PAGER, it's looking farther down 
the line and finding something that works from that fallback list. So 
the question is what is your $PAGER set to that _isn't_ working with 
images?

-Brett

**Comment by rwmitchell** [comment]
I have PAGER set to colorize_less, from an OMZ plugin.   It ultimately is still using less, which is why I was confused, but must have different options set.  Setting PAGER to less does work, but I'm still confused.

If I just run: ```imgcat foo.png | less``` I get the iTerm2 escape sequence for the image, not the image.  What magic is mdless using?

**Comment by ttscoff** [comment]
mdless uses the flags -Xr if less is specified. Try adding `-Xr` to your 
PAGER setting and see if you get better results.

-Brett

**Comment by rwmitchell** [comment]
Indeed, -Xr is the magic.
