### ISSUE TITLE
Display multiple sections with '-s'

### ISSUE THREAD

**Issue by rwmitchell** [ttscoff/mdless#86]
How difficult would it be to allow using '-s' or multiple values with '-s' to display multiple, but not all, sections in a file?

**Comment by ttscoff** [comment]
Not easy, but not impossible. I'll consider it for my next round of 
feature additions.

-Brett

**Comment by ttscoff** [comment]
v2.8.1 allows multiple sections for most commands, including show, recent, today, etc. Will be available shortly.

**Comment by rwmitchell** [comment]
v2.8.1 ????

I have: mdless 1.0.32

**Comment by ttscoff** [comment]
Oh man, I misread this as a request for another utility, doing, and spent an hour making that happen. I’ll have to get back to this for mdless next time.

- Brett

**Comment by rwmitchell** [comment]
That's funny. Not for you, of course.

I was trying to imagine all the other new features you had already added but not pushed.

**Comment by ttscoff** [comment]
Ok, for real this time. Version 1.0.33 now allows a comma separated list of sections to display, and will display them in the order specified, e.g. `mdless FILENAME -s 2,3`. Please test and let me know if it suits your needs.

**Comment by rwmitchell** [comment]
Looks great!! Thanks!
