### ISSUE TITLE
Rendering headers & paragraphs

### ISSUE THREAD

**Issue by MimiKLM** [ttscoff/mdless#87]
With default installation of mdless (no mdless.theme changes) and having the org file in emacs like that:

<img width="578" alt="Screenshot 2023-07-07 at 21 59 12" src="https://github.com/ttscoff/mdless/assets/59035458/b8305339-23bd-4f26-8a5a-8b3e2c155b79">

after calling mdless as `mdless -P myorgFile.org` I'm getting the rendering like below:

<img width="567" alt="Screenshot 2023-07-07 at 22 03 58" src="https://github.com/ttscoff/mdless/assets/59035458/b082999a-75c0-4267-988f-5b2168b495de">

Only one thing I got formatted is h1 bullet point.

Why?

I'm using macOS 13.4 iTerm2 and warp. Effect on both terminals is the same.

**Comment by ttscoff** [comment]
This is not recognized Markdown formatting. Mdless makes no attempt to work with org mode.

Thanks,
Brett

**Comment by MimiKLM** [comment]
Ok, explanation accepted.
