### ISSUE TITLE
In contrast to less: mdless doesn't adapt to changing view port of terminal

### ISSUE THREAD

**Issue by leder11011** [ttscoff/mdless#88]
As seen in the two screenshots less uses the full width of the terminal when the viewport is switched from portrait to landscape and mdless keeps the portrait formatting.

Thanks for a great app!

Unfortunately I cannot attach screenshots in GitHub mobile app.

**Comment by leder11011** [comment]
Could you please fix this issue for gem package? It's annoying and doesn't offer "a replacement for less".

**Comment by ttscoff** [comment]
mdless calculates its line wrapping and code formatting based on the width of the screen at the time the command is run. There is no way to output what it does in a way that will wrap if the screen width is changed.

**Comment by leder11011** [comment]
Hello Brett,

Thank you for your answer and your commitment!

It's exactly what less does: it respects view port changes of the terminal
on the fly.

Please reconsider!

Bye Gerrit
 P. S. Screenshots attached

Brett Terpstra ***@***.***> schrieb am Fr., 15. Sept. 2023,
14:39:

**Comment by leder11011** [comment]
![Screenshot_2023-08-09-16-32-42-68_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/ttscoff/mdless/assets/3330116/3891d18a-8c97-4081-bae6-42feb3e92da6)

![Screenshot_2023-08-10-10-21-10-48_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/ttscoff/mdless/assets/3330116/4a597e46-e0d1-45cc-84cd-d48ad24c89f3)

![Screenshot_2023-08-09-16-33-42-23_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/ttscoff/mdless/assets/3330116/06fc8f41-4f73-413c-afae-627e0e895e45)

**Comment by leder11011** [comment]
Bump @ttscoff

**Comment by leder11011** [comment]
thank you for version 2.1.13!

Unfortunately I get a runtime error on Android termux, which was working fine on the previous version 1.0.37

Error is as follows:
console.rb:778:in '*': negative argument (Argument Error)

Please let me know if you need a stacktrace - I can send a screenshot, copy&pasta is a bit difficult on Android smartphone...

**Comment by leder11011** [comment]
https://photos.app.goo.gl/82WxiKzHutq3KQdcA

**Comment by leder11011** [comment]
Thank you for version 2.1.23

I have a regression now:

Opening mdless already in landscape mode uses the landscape width only partly, cp. Screenshot 

![Screenshot_20231204-195932.png](https://github.com/ttscoff/mdless/assets/3330116/464f9efb-46af-4eeb-9f3f-60e74812e0da)

**Comment by ttscoff** [comment]
Is there a width setting hardcoded in ~/.config/mdless/config.yml? It may have stored a current column width and then defaulted to it. If that’s the case I should remove that from automatic saving, so let me know.

Thanks,
Brett

**Comment by leder11011** [comment]
Hello Brett,

deleting the line `:width:` from `config.yml` did the trick! Please remove it from auto saving, too.

Best regards
Gerrit

**Comment by ttscoff** [comment]
I will delete, but it will mean any time a user wants to set a permanent 
width setting they'll have to manually include the :width: key, and 
running --update-theme will delete it. I'll just document it well.

-Brett

**Comment by leder11011** [comment]
Thank you!

2.1.25 is breaking with runtime error

![Screenshot_20231205-141907.png](https://github.com/ttscoff/mdless/assets/3330116/be9aa3f8-7e41-49e6-b470-14b558fca651)

**Comment by ttscoff** [comment]
I’m going to put some more time into table formatting soon.

Thanks,
Brett

**Comment by leder11011** [comment]
> ![error2.md](https://github.com/ttscoff/mdless/files/13561240/error2.md)
> 
> 
> 

Please have a look...

**Comment by leder11011** [comment]
Thank you @ttscoff !

the configuration of the screenwidth fixes this for me now! It is not calculated on the fly on my smartphone, but what the heck: I only use app Termux in landscape only! So I am more than satisfied with your app mdless! Keep up the good faith!

Gerrit
