### ISSUE TITLE
Table inherit its size from previous table in the file

### ISSUE THREAD

**Issue by fdufnews** [ttscoff/mdless#92]
mdless 2.0.18
Table inherit its size from a previously displayed one and columns are added
![Clipboard 1](https://github.com/ttscoff/mdless/assets/4077715/604acb9d-a07b-4ee1-8891-e8c58ebea1b7)
I am not sure it is a bug or a feature

**Comment by ttscoff** [comment]
Definitely a bug. I'll try to track it down today.

-Brett

**Comment by fdufnews** [comment]
I just did an update, now 2.0.23, and it works fine.
Thank-you for your prompt response

**Comment by fdufnews** [comment]
I think one can be closed too
