### ISSUE TITLE
Not compatible with watch

### ISSUE THREAD

**Issue by thiklock** [ttscoff/mdless#93]
# Not compatible with command watch
No major issue but I was hoping to me be able to use this  beauty with the watch command, so I can edit and see the change another screen.

I tried but got something very differently from my expectations.

<img width="696" alt="image" src="https://github.com/ttscoff/mdless/assets/43356541/752f3bc3-ac6d-4f0e-93df-a77712126d7c">

I wish to know if there is any other way to accomplish this. 

Thanks in advance!

Configs:
mdless version: mdless 2.0.18 
On MacOS

**Comment by ttscoff** [comment]
I don’t know what watch is, but you need your pager to interpret escape codes. For less this means using -x. Does watch have a similar flag?

Thanks,
Brett

**Comment by ttscoff** [comment]
I guess alternatively you could run mdless with —no-color and just avoid all the escape sequences entirely, but it would just be plain text output.

Thanks,
Brett
