### ISSUE TITLE
Strange behaviour when opening in a "small terminal"

### ISSUE THREAD

**Issue by fdufnews** [ttscoff/mdless#94]
Hi,
mdless 2.0.23
Another problem with the tables.
When I open a file in a 80x24 terminal the long lines wrap as intended.
When I then extend the terminal window to say 132 the tables does not extend apart from the dashed lines even if the config.yml contains :width: 132
![Clipboard 1](https://github.com/ttscoff/mdless/assets/4077715/f07c84c7-45d9-40e4-af8c-b15864cf67d3)

But, if I open the same file in the same 80x24 terminal with the -w 132 option in the command line, the lines wrap but when I extend the window they are displayed as expected
![Clipboard 2](https://github.com/ttscoff/mdless/assets/4077715/b96ba5e5-4294-4e93-ba2b-589b2c0ffdd8)

So it seems there is a problem with the :width: 132 in the config file and the way it is used.

**Comment by fdufnews** [comment]
>If the specified number of columns is greater than the width of the
screen, it switches to using the screen width instead.

OK, but if I start with the default size of my terminal which is 80x24
- if I put -w 132 in the command line the lines wrap but they are following the size of the window (maybe it is a side effect with gnome terminal)
- if  I put no option but :width: 132 is in the config file it has no effect. And as I understand it -w 132 in the command line or :width: 132 in config.yml should tend to the same behaviour

**Comment by ttscoff** [comment]
I think I found the issue. Please test 2.1.3.

-Brett

**Comment by fdufnews** [comment]
Hi,

It works now.
Thank you
Best regards
