### ISSUE TITLE
Is v2.1.3 the latest release?

### ISSUE THREAD

**Issue by p-linnane** [ttscoff/mdless#95]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While updating mdless we noticed the v2.1.x tags don't have releases associated with them. Is v2.1.3 the latest release? Or should we still be on the v2.0.x releases? Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/155794

**Comment by ttscoff** [comment]
2.1.3 is the latest. I must have messed up something in my deploy script when I switched to using git-flow. Will get it back to generating releases later today.

Thanks,
Brett

**Comment by p-linnane** [comment]
Thank you!

**Comment by ttscoff** [comment]
@p-linnane is it you I have to thank for creating the mdless formula?

**Comment by p-linnane** [comment]
It was created by @bugfest in https://github.com/Homebrew/homebrew-core/pull/121410.

**Comment by ttscoff** [comment]
Thanks!
