### ISSUE TITLE
empty character in codeblock doesn't work anymore

### ISSUE THREAD

**Issue by fdufnews** [ttscoff/mdless#96]
mdless 2.1.24

In mdless.theme, empty character: in codeblock does not work anymore.
Empty character still displays the > at beginning of line
Changing character to say "+" or "" makes the block of code flashing.

**Comment by ttscoff** [comment]
works for me, are you including empty quotes?

**Comment by fdufnews** [comment]
I tried either of empty quotes or nothing following character:
when I use empty quotes the > is not displayed but the codeblock blinks.
when I use nothing following character: the > is displayed

**Comment by ttscoff** [comment]
The code block blinks?

**Comment by fdufnews** [comment]
Yes it does from the first space to the end of the line
![image](https://github.com/ttscoff/mdless/assets/4077715/b1c43ef1-9ee7-42b6-94cd-ce22b3a42a43)

![image](https://github.com/ttscoff/mdless/assets/4077715/bcfa82ab-1cd5-4f73-bc61-0cd7e424a86e)

**Comment by ttscoff** [comment]
And this blinking doesn't happen if there's a character specified? That's so weird.

**Comment by ttscoff** [comment]
What do you have `marker:` set to in your theme?

**Comment by fdufnews** [comment]
Here is the theme I am using (renamed as .txt as Github forbid .theme extension).
[mdless.txt](https://github.com/ttscoff/mdless/files/13688004/mdless.txt)

If I am right it is the default one apart from one or two value

**Comment by ttscoff** [comment]
Does it make any difference if you try a different Pygments theme? Because it’s happening in the middle of a line, mdless shouldn’t be inserting any escape codes. Those escapes would have to come from what pygments is outputting, unless I’m missing something.

- Brett

**Comment by fdufnews** [comment]
I have tried some others theme files.
With some themes only the comments are blinking.

Found something !!!!!
There is a compatibility issue with Gnome Terminal.
I just found that there is an option in the gnome terminal that enables/disables blinking text. That option is enabled by default and when disabled I have no more problem whichever theme I use. Even the character: is working has expected.
It is the first time that I see blinking text in the terminal.
Maybe it is linked to some escape code sent by Pygments.
Definitively not a problem with mdless, I think.
Maybe you can close this issue.

**Comment by ttscoff** [comment]
Cool. Thanks for following up.
