### ISSUE TITLE
404 error from gem file on "rake install"

### ISSUE THREAD

**Issue by U3055** [ttscoff/mdless#99]
I performed `git clone https://github.com/ttscoff/mdless` and `rake install` got the following error:

`gem install pkg/*.gem
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://index.rubygems.org/info/pkg/*.gem)
rake aborted!
Command failed with status (1): [gem install pkg/*.gem...]
/home/user/mdless/Rakefile:27:in `block in <top (required)>'
Tasks: TOP => install
(See full trace by running task with --trace)
`

I checked and indeed, I got 404 error on https://index.rubygems.org/info/pkg/*.gem

any idea how to fix that ?

**Comment by ttscoff** [comment]
Rake install is only for testing purposes, and requires running rake package first. You likely want ‘gem install’.

- Brett
